version: 2.1
jobs:
  build:
    docker:
      - image: node/base:16.16.0
    steps:
      - run:
          name: Lighthouse CI
          commands: |
            cd lighthouse
            npm run lighthouse
